package com.example.pokerecycler

var categoriasList = mutableListOf(
    Categorias("Abc", "https://www.pngmart.com/files/21/ABC-PNG-Isolated-Image.png",
        mutableListOf(
            Palabras("a", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/a.JPG", false),
            Palabras("b", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/b.JPG", false),
            Palabras("c", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/c.JPG", false),
            Palabras("d", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/d.JPG", false),
            Palabras("e", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/e.JPG", false),
            Palabras("f", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/f.JPG", false),
            Palabras("g", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/g.JPG", false),
            Palabras("h", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/h.JPG", false),
            Palabras("i", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/i.JPG", false),
            Palabras("J", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/J_Web.m4v", true),
            Palabras("K", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/K_Web.m4v", true),
            Palabras("l", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/l.JPG", false),
            Palabras("Ll", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/Ll_Web.m4v", true),
            Palabras("m", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/m.JPG", false),
            Palabras("n", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/n.JPG", false),
            Palabras("Nie", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/Nie_Web.m4v", true),
            Palabras("o", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/o.JPG", false),
            Palabras("p", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/p.JPG", false),
            Palabras("Q", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/Q_Web.m4v", true),
            Palabras("r", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/r.JPG", false),
            Palabras("Rr", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/Rr_Web.m4v", true),
            Palabras("s", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/s.JPG", false),
            Palabras("t", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/t.JPG", false),
            Palabras("u", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/u.JPG", false),
            Palabras("v", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/v.JPG", false),
            Palabras("w", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/w.JPG", false),
            Palabras("X", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/X_Web.m4v", true),
            Palabras("y", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/y.jpg", false),
            Palabras("Z", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Abecedario_Web/Z_Web.m4v", true)
        )
    ),
    Categorias("Animales","https://cdn-icons-png.flaticon.com/512/3397/3397536.png",
        mutableListOf(
            Palabras("Abeja", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Abeja_Web.m4v", true),
            Palabras("Aguila", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Aguila_Web.m4v", true),
            Palabras("Arana", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Arana_Web.m4v", true),
            Palabras("Ardilla", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Ardilla_Web.m4v", true),
            Palabras("Burro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Burro_Web.m4v", true),
            Palabras("Caballo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Caballo_Web.m4v", true),
            Palabras("Cerdo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Cerdo_Web.m4v", true),
            Palabras("Chango", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Chango_Web.m4v", true),
            Palabras("Conejo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Conejo_Web.m4v", true),
            Palabras("Gato", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Gato_Web.m4v", true),
            Palabras("Gorila", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Gorila_Web.m4v", true),
            Palabras("Gusano", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Gusano_Web.m4v", true),
            Palabras("Jirafa", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Jirafa_Web.m4v", true),
            Palabras("Leon", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Leon_Web.m4v", true),
            Palabras("Mariposa", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Mariposa_Web.m4v", true),
            Palabras("Oso", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Oso_Web.m4v", true),
            Palabras("Pajaro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Pajaro_Web.m4v", true),
            Palabras("Paloma", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Paloma_Web.m4v", true),
            Palabras("Pato", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Pato_Web.m4v", true),
            Palabras("Perro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Perro_Web.m4v", true),
            Palabras("Pez", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Pez_Web.m4v", true),
            Palabras("Raton", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Raton_Web.m4v", true),
            Palabras("Tigre", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Tigre_Web.m4v", true),
            Palabras("Toro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Toro_Web.m4v", true),
            Palabras("Tortuga", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Tortuga_Web.m4v", true),
            Palabras("Vaca", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Vaca_Web.m4v", true),
            Palabras("Vibora", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Animales_Web/Vibora_Web.m4v", true)
        )
    ),
    Categorias("Colores","https://cdn-icons-png.flaticon.com/512/3199/3199937.png",
        mutableListOf(
            Palabras("Amarillo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Colores_Web/Amarillo_Web.m4v", true),
            Palabras("Azul", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Colores_Web/Azul_Web.m4v", true),
            Palabras("Blanco", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Colores_Web/Blanco_Web.m4v", true),
            Palabras("Cafe", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Colores_Web/Cafe_Web.m4v", true),
            Palabras("Gris", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Colores_Web/Gris_Web.m4v", true),
            Palabras("Morado", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Colores_Web/Morado_Web.m4v", true),
            Palabras("Naranja", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Colores_Web/Naranja_Web.m4v", true),
            Palabras("Negro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Colores_Web/Negro_Web.m4v", true),
            Palabras("Oro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Colores_Web/Oro_Web.m4v", true),
            Palabras("Plata", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Colores_Web/Plata_Web.m4v", true),
            Palabras("Rojo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Colores_Web/Rojo_Web.m4v", true),
            Palabras("Rosa", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Colores_Web/Rosa_Web.m4v", true),
            Palabras("Verde", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Colores_Web/Verde_Web.m4v", true)
        )
    ),
    Categorias("Comida","https://cdn-icons-png.flaticon.com/512/706/706164.png",
        mutableListOf(
            Palabras("Aceite", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Aceite_Web.m4v", true),
            Palabras("Agua", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Agua_Web.m4v", true),
            Palabras("Arroz", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Arroz_Web.m4v", true),
            Palabras("Azucar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Azucar_Web.m4v", true),
            Palabras("Cafe", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Cafe_Web.m4v", true),
            Palabras("Caldo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Caldo_Web.m4v", true),
            Palabras("Carne", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Carne_Web.m4v", true),
            Palabras("Cerveza", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Cerveza_Web.m4v", true),
            Palabras("Chile", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Chile_Web.m4v", true),
            Palabras("Chocolate", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Chocolate_Web.m4v", true),
            Palabras("Cocacola", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Cocacola_Web.m4v", true),
            Palabras("Dulce", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Dulce_Web.m4v", true),
            Palabras("Ensalada", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Ensalada_Web.m4v", true),
            Palabras("Frijol", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Frijol_Web.m4v", true),
            Palabras("Fruta", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Fruta_Web.m4v", true),
            Palabras("Galleta", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Galleta_Web.m4v", true),
            Palabras("Hamburguesa", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Hamburguesa_Web.m4v", true),
            Palabras("Huevo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Huevo_Web.m4v", true),
            Palabras("Leche", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Leche_Web.m4v", true),
            Palabras("Pan", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Pan_Web.m4v", true),
            Palabras("Pastel", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Pastel_Web.m4v", true),
            Palabras("Pescado", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Pescado_Web.m4v", true),
            Palabras("Pizza", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Pizza_Web.m4v", true),
            Palabras("Pollo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Pollo_Web.m4v", true),
            Palabras("Queso", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Queso_Web.m4v", true),
            Palabras("Refresco", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Refresco_Web.m4v", true),
            Palabras("Sopa", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Sopa_Web.m4v", true),
            Palabras("Taco", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Taco_Web.m4v", true),
            Palabras("Tortilla", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Tortilla_Web.m4v", true),
            Palabras("Verdura", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Comida_Web/Verdura_Web.m4v", true),
        )
    ),
    Categorias("Cuerpo","https://cdn-icons-png.flaticon.com/512/4807/4807844.png",
        mutableListOf(
            Palabras("Boca", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Cuerpo_Web/Boca_Web.m4v", true),
            Palabras("Cabeza", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Cuerpo_Web/Cabeza_Web.m4v", true),
            Palabras("Cara", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Cuerpo_Web/Cara_Web.m4v", true),
            Palabras("Cejas", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Cuerpo_Web/Cejas_Web.m4v", true),
            Palabras("Corazon", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Cuerpo_Web/Corazon_Web.m4v", true),
            Palabras("Estomago", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Cuerpo_Web/Estomago_Web.m4v", true),
            Palabras("Hueso", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Cuerpo_Web/Hueso_Web.m4v", true),
            Palabras("Mano", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Cuerpo_Web/Mano_Web.m4v", true),
            Palabras("Nariz", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Cuerpo_Web/Nariz_Web.m4v", true),
            Palabras("Ojos", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Cuerpo_Web/Ojos_Web.m4v", true),
            Palabras("Oreja", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Cuerpo_Web/Oreja_Web.m4v", true),
            Palabras("Pestanas", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Cuerpo_Web/Pestanas_Web.m4v", true),
            Palabras("Piel", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Cuerpo_Web/Piel_Web.m4v", true),
            Palabras("Pies", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Cuerpo_Web/Pies_Web.m4v", true),
            Palabras("Sangre", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Cuerpo_Web/Sangre_Web.m4v", true),
        )
    ),
    Categorias(
        "Días de la semana", "https://cdn-icons-png.flaticon.com/512/2055/2055647.png",
        mutableListOf(
            Palabras("Domingo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_DiasDeLaSemana_Web/Domingo_Web.m4v", true),
            Palabras("Jueves", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_DiasDeLaSemana_Web/Jueves_Web.m4v", true),
            Palabras("Lunes", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_DiasDeLaSemana_Web/Lunes_Web.m4v", true),
            Palabras("Martes", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_DiasDeLaSemana_Web/Martes_Web.m4v", true),
            Palabras("Miercoles", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_DiasDeLaSemana_Web/Miercoles_Web.m4v", true),
            Palabras("Sabado", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_DiasDeLaSemana_Web/Sabado_Web.m4v", true),
            Palabras("Viernes", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_DiasDeLaSemana_Web/Viernes_Web.m4v", true),
        )
    ),
    Categorias("Frutas","https://cdn-icons-png.flaticon.com/512/1617/1617560.png",
        mutableListOf(
            Palabras("Almendra", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Almendra_Web.m4v", true),
            Palabras("Cereza", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Cereza_Web.m4v", true),
            Palabras("Coco", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Coco_Web.m4v", true),
            Palabras("Durazno", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Durazno_Web.m4v", true),
            Palabras("Fresa", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Fresa_Web.m4v", true),
            Palabras("Guayaba", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Guayaba_Web.m4v", true),
            Palabras("Jamaica", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Jamaica_Web.m4v", true),
            Palabras("Jicama", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Jicama_Web.m4v", true),
            Palabras("Limon", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Limon_Web.m4v", true),
            Palabras("Mango", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Mango_Web.m4v", true),
            Palabras("Manzana", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Manzana_Web.m4v", true),
            Palabras("Melon", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Melon_Web.m4v", true),
            Palabras("Naranja", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Naranja_Web.m4v", true),
            Palabras("Nuez", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Nuez_Web.m4v", true),
            Palabras("Papaya", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Papaya_Web.m4v", true),
            Palabras("Pera", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Pera_Web.m4v", true),
            Palabras("Pina", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Pina_Web.m4v", true),
            Palabras("Platano", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Platano_Web.m4v", true),
            Palabras("Sandia", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Sandia_Web.m4v", true),
            Palabras("Tamarindo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Tamarindo_Web.m4v", true),
            Palabras("Toronja", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Toronja_Web.m4v", true),
            Palabras("Uva", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Frutas_Web/Uva_Web.m4v", true),
        )
    ),
    Categorias("Hogar","https://cdn-icons-png.flaticon.com/512/2544/2544056.png",
        mutableListOf(
            Palabras("Bano", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Bano_Web.m4v", true),
            Palabras("Caja", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Caja_Web.m4v", true),
            Palabras("Cama", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Cama_Web.m4v", true),
            Palabras("Casa", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Casa_Web.m4v", true),
            Palabras("Celular", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Celular_Web.m4v", true),
            Palabras("Cocina", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Cocina_Web.m4v", true),
            Palabras("Computadora", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Computadora_Web.m4v", true),
            Palabras("Cuarto", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Cuarto_Web.m4v", true),
            Palabras("Cuchara", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Cuchara_Web.m4v", true),
            Palabras("Foco", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Foco_Web.m4v", true),
            Palabras("Gas", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Gas_Web.m4v", true),
            Palabras("Impresora", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Impresora_Web.m4v", true),
            Palabras("Lavadora", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Lavadora_Web.m4v", true),
            Palabras("Licuadora", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Licuadora_Web.m4v", true),
            Palabras("Llave", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Llave_Web.m4v", true),
            Palabras("Luz", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Luz_Web.m4v", true),
            Palabras("Mesa", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Mesa_Web.m4v", true),
            Palabras("Plancha", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Plancha_Web.m4v", true),
            Palabras("Plato", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Plato_Web.m4v", true),
            Palabras("Puerta", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Puerta_Web.m4v", true),
            Palabras("Silla", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Silla_Web.m4v", true),
            Palabras("Telefono", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Telefono_Web.m4v", true),
            Palabras("Tenedor", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Tenedor_Web.m4v", true),
            Palabras("Vaso", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Vaso_Web.m4v", true),
            Palabras("Ventana", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Hogar_Web/Ventana_Web.m4v", true),
        )
    ),
    Categorias("Lugares","https://cdn-icons-png.flaticon.com/512/2098/2098316.png",
        mutableListOf(
            Palabras("Antro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Antro_Web.m4v", true),
            Palabras("Banco", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Banco_Web.m4v", true),
            Palabras("Calle", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Calle_Web.m4v", true),
            Palabras("Cantina", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Cantina_Web.m4v", true),
            Palabras("Casa", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Casa_Web.m4v", true),
            Palabras("Centro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Centro_Web.m4v", true),
            Palabras("Cine", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Cine_Web.m4v", true),
            Palabras("Ciudad", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Ciudad_Web.m4v", true),
            Palabras("Edificio", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Edificio_Web.m4v", true),
            Palabras("Escuela", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Escuela_Web.m4v", true),
            Palabras("Fabrica", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Fabrica_Web.m4v", true),
            Palabras("Feria", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Feria_Web.m4v", true),
            Palabras("Fiesta", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Fiesta_Web.m4v", true),
            Palabras("Hotel", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Hotel_Web.m4v", true),
            Palabras("Iglesia", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Iglesia_Web.m4v", true),
            Palabras("Mercado", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Mercado_Web.m4v", true),
            Palabras("Museo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Museo_Web.m4v", true),
            Palabras("Restaurante", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Restaurante_Web.m4v", true),
            Palabras("Teatro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Teatro_Web.m4v", true),
            Palabras("Tienda", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Lugares_Web/Tienda_Web.m4v", true),
        )
    ),
    Categorias("Meses del Año", "https://cdn-icons-png.flaticon.com/512/3652/3652191.png",
        mutableListOf(
            Palabras("Abril", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_MesesDelAnio_Web/Abril_Web.m4v", true),
            Palabras("Agosto", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_MesesDelAnio_Web/Agosto_Web.m4v", true),
            Palabras("Diciembre", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_MesesDelAnio_Web/Diciembre_Web.m4v", true),
            Palabras("Enero", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_MesesDelAnio_Web/Enero_Web.m4v", true),
            Palabras("Febrero", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_MesesDelAnio_Web/Febrero_Web.m4v", true),
            Palabras("Julio", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_MesesDelAnio_Web/Julio_Web.m4v", true),
            Palabras("Junio", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_MesesDelAnio_Web/Junio_Web.m4v", true),
            Palabras("Marzo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_MesesDelAnio_Web/Marzo_Web.m4v", true),
            Palabras("Mayo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_MesesDelAnio_Web/Mayo_Web.m4v", true),
            Palabras("Noviembre", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_MesesDelAnio_Web/Noviembre_Web.m4v", true),
            Palabras("Octubre", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_MesesDelAnio_Web/Octubre_Web.m4v", true),
            Palabras("Septiembre", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_MesesDelAnio_Web/Septiembre_Web.m4v", true),
        )
    ),
    Categorias("Números","https://cdn-icons-png.flaticon.com/512/1519/1519407.png",
        mutableListOf(
            Palabras("0", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/0.JPG", false),
            Palabras("1", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/1.JPG", false),
            Palabras("1000000", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/1000000_Web.m4v", true),
            Palabras("1000", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/1000_Web.m4v", true),
            Palabras("100", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/100_Web.m4v", true),
            Palabras("10", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/10_Web.m4v", true),
            Palabras("11", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/11_Web.m4v", true),
            Palabras("12", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/12_Web.m4v", true),
            Palabras("13", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/13_Web.m4v", true),
            Palabras("14", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/14_Web.m4v", true),
            Palabras("15", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/15_Web.m4v", true),
            Palabras("16", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/16_Web.m4v", true),
            Palabras("17", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/17_Web.m4v", true),
            Palabras("18", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/18_Web.m4v", true),
            Palabras("19", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/19_Web.m4v", true),
            Palabras("2", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/2.JPG", false),
            Palabras("200", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/200_Web.m4v", true),
            Palabras("20", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/20_Web.m4v", true),
            Palabras("25", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/25_Web.m4v", true),
            Palabras("3", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/3.JPG", false),
            Palabras("300", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/300_Web.m4v", true),
            Palabras("30", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/30_Web.m4v", true),
            Palabras("4", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/4.JPG", false),
            Palabras("400", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/400_Web.m4v", true),
            Palabras("40", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/40_Web.m4v", true),
            Palabras("5", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/5.JPG", false),
            Palabras("500", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/500_Web.m4v", true),
            Palabras("50", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/50_Web.m4v", true),
            Palabras("6", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/6.JPG", false),
            Palabras("600", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/600_Web.m4v", true),
            Palabras("60", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/60_Web.m4v", true),
            Palabras("7", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/7.JPG", false),
            Palabras("700", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/700_Web.m4v", true),
            Palabras("70", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/70_Web.m4v", true),
            Palabras("8", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/8.JPG", false),
            Palabras("800", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/800_Web.m4v", true),
            Palabras("80", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Numero_Web/80_Web.m4v", true),
        )
    ),
    Categorias("Personas","https://cdn-icons-png.flaticon.com/512/2566/2566158.png",
        mutableListOf(
            Palabras("Abuela", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Abuela_Web.m4v", true),
            Palabras("Abuelo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Abuelo_Web.m4v", true),
            Palabras("Adulto", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Adulto_Web.m4v", true),
            Palabras("Amante", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Amante_Web.m4v", true),
            Palabras("Amiga", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Amiga_Web.m4v", true),
            Palabras("Amigo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Amigo_Web.m4v", true),
            Palabras("Anciano", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Anciano_Web.m4v", true),
            Palabras("Bebe", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Bebe_Web.m4v", true),
            Palabras("Bisabuela", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Bisabuela_Web.m4v", true),
            Palabras("Bisabuelo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Bisabuelo_Web.m4v", true),
            Palabras("Bisnieta", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Bisnieta_Web.m4v", true),
            Palabras("Bisnieto", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Bisnieto_Web.m4v", true),
            Palabras("Ciego", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Ciego_Web.m4v", true),
            Palabras("Companero", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Companero_Web.m4v", true),
            Palabras("Cunada", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Cunada_Web.m4v", true),
            Palabras("Cunado", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Cunado_Web.m4v", true),
            Palabras("Divorciado", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Divorciado_Web.m4v", true),
            Palabras("Esposa", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Esposa_Web.m4v", true),
            Palabras("Esposo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Esposo_Web.m4v", true),
            Palabras("Hermana", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Hermana_Web.m4v", true),
            Palabras("Hermano", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Hermano_Web.m4v", true),
            Palabras("Hijastra", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Hijastra_Web.m4v", true),
            Palabras("Hijastro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Hijastro_Web.m4v", true),
            Palabras("Hija", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Hija_Web.m4v", true),
            Palabras("Hijo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Hijo_Web.m4v", true),
            Palabras("Hombre", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Hombre_Web.m4v", true),
            Palabras("Huerfano", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Huerfano_Web.m4v", true),
            Palabras("Madrastra", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Madrastra_Web.m4v", true),
            Palabras("Madrina", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Madrina_Web.m4v", true),
            Palabras("Mama", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Mama_Web.m4v", true),
            Palabras("Matrimonio", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Matrimonio_Web.m4v", true),
            Palabras("Mediahermana", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Mediahermana_Web.m4v", true),
            Palabras("Mediohermano", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Mediohermano_Web.m4v", true),
            Palabras("Mujer", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Mujer_Web.m4v", true),
            Palabras("Nieta", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Nieta_Web.m4v", true),
            Palabras("Nieto", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Nieto_Web.m4v", true),
            Palabras("Nina", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Nina_Web.m4v", true),
            Palabras("Nino", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Nino_Web.m4v", true),
            Palabras("Novia", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Novia_Web.m4v", true),
            Palabras("Novio", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Novio_Web.m4v", true),
            Palabras("Nuera", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Nuera_Web.m4v", true),
            Palabras("Oyente", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Oyente_Web.m4v", true),
            Palabras("Padrastro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Padrastro_Web.m4v", true),
            Palabras("Padrino", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Padrino_Web.m4v", true),
            Palabras("Papa", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Papa_Web.m4v", true),
            Palabras("Pareja", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Pareja_Web.m4v", true),
            Palabras("Persona", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Persona_Web.m4v", true),
            Palabras("Prima", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Prima_Web.m4v", true),
            Palabras("Primo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Primo_Web.m4v", true),
            Palabras("Senora", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Senora_Web.m4v", true),
            Palabras("Senorita", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Senorita_Web.m4v", true),
            Palabras("Senor", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Senor_Web.m4v", true),
            Palabras("Separado", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Separado_Web.m4v", true),
            Palabras("Sobrina", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Sobrina_Web.m4v", true),
            Palabras("Sobrino", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Sobrino_Web.m4v", true),
            Palabras("Soltero", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Soltero_Web.m4v", true),
            Palabras("Sordo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Sordo_Web.m4v", true),
            Palabras("Suegra", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Suegra_Web.m4v", true),
            Palabras("Suegro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Suegro_Web.m4v", true),
            Palabras("Tia", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Tia_Web.m4v", true),
            Palabras("Tio", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Tio_Web.m4v", true),
            Palabras("Unionlibre", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Personas_Web/Unionlibre_Web.m4v", true),
        )
    ),
    Categorias("Preguntas","https://cdn-icons-png.flaticon.com/512/5726/5726678.png",
        mutableListOf(
            Palabras("Como", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Preguntas_Web/Como_Web.m4v", true),
            Palabras("Cual", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Preguntas_Web/Cual_Web.m4v", true),
            Palabras("Cuando", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Preguntas_Web/Cuando_Web.m4v", true),
            Palabras("Cuanto", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Preguntas_Web/Cuanto_Web.m4v", true),
            Palabras("Donde", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Preguntas_Web/Donde_Web.m4v", true),
            Palabras("Paraque", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Preguntas_Web/Paraque_Web.m4v", true),
            Palabras("Porque", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Preguntas_Web/Porque_Web.m4v", true),
            Palabras("Que", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Preguntas_Web/Que_Web.m4v", true),
            Palabras("Quien", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Preguntas_Web/Quien_Web.m4v", true),
        )
    ),
    Categorias("Preposiciones","https://cdn-icons-png.flaticon.com/512/4158/4158760.png",
        mutableListOf(
            Palabras("Abajo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Abajo_Web.m4v", true),
            Palabras("Aburrido", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Aburrido_Web.m4v", true),
            Palabras("Accidente", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Accidente_Web.m4v", true),
            Palabras("Adentro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Adentro_Web.m4v", true),
            Palabras("Afortunado", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Afortunado_Web.m4v", true),
            Palabras("Alegredivertido", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Alegredivertido_Web.m4v", true),
            Palabras("Algunos", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Algunos_Web.m4v", true),
            Palabras("Altoestatura", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Altoestatura_Web.m4v", true),
            Palabras("Amable", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Amable_Web.m4v", true),
            Palabras("Antes", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Antes_Web.m4v", true),
            Palabras("Arriba", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Arriba_Web.m4v", true),
            Palabras("Asustado", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Asustado_Web.m4v", true),
            Palabras("Atencionatento", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Atencionatento_Web.m4v", true),
            Palabras("Baboso", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Baboso_Web.m4v", true),
            Palabras("Bonito", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Bonito_Web.m4v", true),
            Palabras("Broma", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Broma_Web.m4v", true),
            Palabras("Bueno", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Bueno_Web.m4v", true),
            Palabras("Cada", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Cada_Web.m4v", true),
            Palabras("Caliente", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Caliente_Web.m4v", true),
            Palabras("Cansado", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Cansado_Web.m4v", true),
            Palabras("Carino", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Carino_Web.m4v", true),
            Palabras("Celoso", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Celoso_Web.m4v", true),
            Palabras("Chaparro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Chaparro_Web.m4v", true),
            Palabras("Chistoso", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Chistoso_Web.m4v", true),
            Palabras("Cobarde", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Cobarde_Web.m4v", true),
            Palabras("Contento", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Contento_Web.m4v", true),
            Palabras("Curioso", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Curioso_Web.m4v", true),
            Palabras("Debil", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Debil_Web.m4v", true),
            Palabras("Decente", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Decente_Web.m4v", true),
            Palabras("Delgado", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Delgado_Web.m4v", true),
            Palabras("Despacio", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Despacio_Web.m4v", true),
            Palabras("Diferente", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Diferente_Web.m4v", true),
            Palabras("Dificil", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Dificil_Web.m4v", true),
            Palabras("Diploma", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Diploma_Web.m4v", true),
            Palabras("Duda", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Duda_Web.m4v", true),
            Palabras("Egoista", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Egoista_Web.m4v", true),
            Palabras("Ejemplo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Ejemplo_Web.m4v", true),
            Palabras("Ejercicio", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Ejercicio_Web.m4v", true),
            Palabras("Enojado", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Enojado_Web.m4v", true),
            Palabras("Envidia", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Envidia_Web.m4v", true),
            Palabras("Especial", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Especial_Web.m4v", true),
            Palabras("Facil", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Facil_Web.m4v", true),
            Palabras("Falso", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Falso_Web.m4v", true),
            Palabras("Feliz", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Feliz_Web.m4v", true),
            Palabras("Feo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Feo_Web.m4v", true),
            Palabras("Flojo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Flojo_Web.m4v", true),
            Palabras("Fuerte", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Fuerte_Web.m4v", true),
            Palabras("Fuerza", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Fuerza_Web.m4v", true),
            Palabras("Gordo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Gordo_Web.m4v", true),
            Palabras("Gratis", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Gratis_Web.m4v", true),
            Palabras("Grosero", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Grosero_Web.m4v", true),
            Palabras("Guapo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Guapo_Web.m4v", true),
            Palabras("Hambre", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Hambre_Web.m4v", true),
            Palabras("Historia", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Historia_Web.m4v", true),
            Palabras("Humilde", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Humilde_Web.m4v", true),
            Palabras("Importante", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Importante_Web.m4v", true),
            Palabras("Inteligente", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Inteligente_Web.m4v", true),
            Palabras("Jamas", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Jamas_Web.m4v", true),
            Palabras("Junta", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Junta_Web.m4v", true),
            Palabras("Junto", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Junto_Web.m4v", true),
            Palabras("Lejos", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Lejos_Web.m4v", true),
            Palabras("Libre", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Libre_Web.m4v", true),
            Palabras("Loco", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Loco_Web.m4v", true),
            Palabras("Lsm", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Lsm_Web.m4v", true),
            Palabras("Malo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Malo_Web.m4v", true),
            Palabras("Mas", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Mas_Web.m4v", true),
            Palabras("Mejor", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Mejor_Web.m4v", true),
            Palabras("Miedo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Miedo_Web.m4v", true),
            Palabras("Necio", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Necio_Web.m4v", true),
            Palabras("No", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/No_Web.m4v", true),
            Palabras("Nuevo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Nuevo_Web.m4v", true),
            Palabras("Nunca", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Nunca_Web.m4v", true),
            Palabras("Ojala", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Ojala_Web.m4v", true),
            Palabras("Paciencia", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Paciencia_Web.m4v", true),
            Palabras("Peor", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Peor_Web.m4v", true),
            Palabras("Pero", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Pero_Web.m4v", true),
            Palabras("Pobre", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Pobre_Web.m4v", true),
            Palabras("Presumido", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Presumido_Web.m4v", true),
            Palabras("Problema", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Problema_Web.m4v", true),
            Palabras("Rapidopronto", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Rapidopronto_Web.m4v", true),
            Palabras("Raro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Raro_Web.m4v", true),
            Palabras("Secreto", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Secreto_Web.m4v", true),
            Palabras("Senaproipa", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Senaproipa_Web.m4v", true),
            Palabras("Senas", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Senas_Web.m4v", true),
            Palabras("Si", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Si_Web.m4v", true),
            Palabras("Sucio", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Sucio_Web.m4v", true),
            Palabras("Suerte", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Suerte_Web.m4v", true),
            Palabras("Todo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Todo_Web.m4v", true),
            Palabras("Tonto", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Tonto_Web.m4v", true),
            Palabras("Travieso", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_PreposicionesAdjetivosSustantivosAdverbios_Web/Travieso_Web.m4v", true),
        )
    ),
    Categorias("Pronombres","https://cdn-icons-png.flaticon.com/512/476/476863.png",
        mutableListOf(
            Palabras("Ella", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Pronombres_Web/Ella_Web.m4v", true),
            Palabras("Ellos", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Pronombres_Web/Ellos_Web.m4v", true),
            Palabras("El", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Pronombres_Web/El_Web.m4v", true),
            Palabras("Nosotros", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Pronombres_Web/Nosotros_Web.m4v", true),
            Palabras("Tu", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Pronombres_Web/Tu_Web.m4v", true),
            Palabras("Ustedes", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Pronombres_Web/Ustedes_Web.m4v", true),
            Palabras("Yo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Pronombres_Web/Yo_Web.m4v", true),
        )
    ),
    Categorias("Ropa","https://cdn-icons-png.flaticon.com/512/3275/3275384.png",
        mutableListOf(
            Palabras("Abrigo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Ropa_Web/Abrigo_Web.m4v", true),
            Palabras("Brasier", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Ropa_Web/Brasier_Web.m4v", true),
            Palabras("Bufanda", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Ropa_Web/Bufanda_Web.m4v", true),
            Palabras("Calzon", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Ropa_Web/Calzon_Web.m4v", true),
            Palabras("Camisa", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Ropa_Web/Camisa_Web.m4v", true),
            Palabras("Corbata", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Ropa_Web/Corbata_Web.m4v", true),
            Palabras("Falda", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Ropa_Web/Falda_Web.m4v", true),
            Palabras("Medias", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Ropa_Web/Medias_Web.m4v", true),
            Palabras("Pantalon", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Ropa_Web/Pantalon_Web.m4v", true),
            Palabras("Tenis", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Ropa_Web/Tenis_Web.m4v", true),
            Palabras("Vestido", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Ropa_Web/Vestido_Web.m4v", true),
            Palabras("Zapatos", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Ropa_Web/Zapatos_Web.m4v", true),
        )
    ),
    Categorias("Saludos","https://cdn-icons-png.flaticon.com/512/1000/1000344.png",
        mutableListOf(
            Palabras("Adios", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Adios_Web.m4v", true),
            Palabras("Bien", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Bien_Web.m4v", true),
            Palabras("Buenasnoches", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Buenasnoches_Web.m4v", true),
            Palabras("Buenastardes", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Buenastardes_Web.m4v", true),
            Palabras("Buenosdias", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Buenosdias_Web.m4v", true),
            Palabras("Comoestas", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Comoestas_Web.m4v", true),
            Palabras("Comotellamas", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Comotellamas_Web.m4v", true),
            Palabras("Denada", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Denada_Web.m4v", true),
            Palabras("Gracias", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Gracias_Web.m4v", true),
            Palabras("Gustodeconocerte", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Gustodeconocerte_Web.m4v", true),
            Palabras("Hola", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Hola_Web.m4v", true),
            Palabras("Mal", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Mal_Web.m4v", true),
            Palabras("Masomenos", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Masomenos_Web.m4v", true),
            Palabras("Nosvemos", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Nosvemos_Web.m4v", true),
            Palabras("Perdon", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Perdon_Web.m4v", true),
            Palabras("Porfavor", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_SaludosCortesias_Web/Porfavor_Web.m4v", true),
        )
    ),
    Categorias("Tiempo","https://cdn-icons-png.flaticon.com/512/2272/2272194.png",
        mutableListOf(
            Palabras("Ahora", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Ahora_Web.m4v", true),
            Palabras("Ahorita", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Ahorita_Web.m4v", true),
            Palabras("Aire", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Aire_Web.m4v", true),
            Palabras("Ano", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Ano_Web.m4v", true),
            Palabras("Antier", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Antier_Web.m4v", true),
            Palabras("Aveces", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Aveces_Web.m4v", true),
            Palabras("Ayer", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Ayer_Web.m4v", true),
            Palabras("Calendario", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Calendario_Web.m4v", true),
            Palabras("Calor", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Calor_Web.m4v", true),
            Palabras("Cumpleanos", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Cumpleanos_Web.m4v", true),
            Palabras("Despues", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Despues_Web.m4v", true),
            Palabras("Dia", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Dia_Web.m4v", true),
            Palabras("Edad", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Edad_Web.m4v", true),
            Palabras("Fecha", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Fecha_Web.m4v", true),
            Palabras("Frio", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Frio_Web.m4v", true),
            Palabras("Futuro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Futuro_Web.m4v", true),
            Palabras("Hasta", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Hasta_Web.m4v", true),
            Palabras("Hora", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Hora_Web.m4v", true),
            Palabras("Hoy", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Hoy_Web.m4v", true),
            Palabras("Invierno", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Invierno_Web.m4v", true),
            Palabras("Manana", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Manana_Web.m4v", true),
            Palabras("Mediodia", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Mediodia_Web.m4v", true),
            Palabras("Mes", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Mes_Web.m4v", true),
            Palabras("Mientras", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Mientras_Web.m4v", true),
            Palabras("Minuto", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Minuto_Web.m4v", true),
            Palabras("Noche", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Noche_Web.m4v", true),
            Palabras("Otono", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Otono_Web.m4v", true),
            Palabras("Otravez", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Otravez_Web.m4v", true),
            Palabras("Otro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Otro_Web.m4v", true),
            Palabras("Pasado", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Pasado_Web.m4v", true),
            Palabras("Presente", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Presente_Web.m4v", true),
            Palabras("Primavera", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Primavera_Web.m4v", true),
            Palabras("Primeravez", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Primeravez_Web.m4v", true),
            Palabras("Proximo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Proximo_Web.m4v", true),
            Palabras("Semana", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Semana_Web.m4v", true),
            Palabras("Siempre", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Siempre_Web.m4v", true),
            Palabras("Tarde", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Tarde_Web.m4v", true),
            Palabras("Temprano", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Tiempo_Web/Temprano_Web.m4v", true),
        )
    ),
    Categorias("Transporte","https://cdn-icons-png.flaticon.com/512/995/995297.png",
        mutableListOf(
            Palabras("Avion", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Transporte_Web/Avion_Web.m4v", true),
            Palabras("Barco", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Transporte_Web/Barco_Web.m4v", true),
            Palabras("Bicicleta", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Transporte_Web/Bicicleta_Web.m4v", true),
            Palabras("Camion", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Transporte_Web/Camion_Web.m4v", true),
            Palabras("Carro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Transporte_Web/Carro_Web.m4v", true),
            Palabras("Cdeautobuses", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Transporte_Web/Cdeautobuses_Web.m4v", true),
            Palabras("Helicoptero", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Transporte_Web/Helicoptero_Web.m4v", true),
            Palabras("Metro", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Transporte_Web/Metro_Web.m4v", true),
            Palabras("Motocicleta", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Transporte_Web/Motocicleta_Web.m4v", true),
            Palabras("Taxi", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Transporte_Web/Taxi_Web.m4v", true),
            Palabras("Transporte", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Transporte_Web/Transporte_Web.m4v", true),
            Palabras("Tren", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Transporte_Web/Tren_Web.m4v", true),
        )
    ),
    Categorias("Verbos Comunes","https://cdn-icons-png.flaticon.com/512/3094/3094845.png",
        mutableListOf(
            Palabras("Aprender", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Aprender_Web.m4v", true),
            Palabras("Avisar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Avisar_Web.m4v", true),
            Palabras("Ayudar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Ayudar_Web.m4v", true),
            Palabras("Comer", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Comer_Web.m4v", true),
            Palabras("Comprar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Comprar_Web.m4v", true),
            Palabras("Creer", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Creer_Web.m4v", true),
            Palabras("Cuidar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Cuidar_Web.m4v", true),
            Palabras("Dar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Dar_Web.m4v", true),
            Palabras("Decir", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Decir_Web.m4v", true),
            Palabras("Descansar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Descansar_Web.m4v", true),
            Palabras("Dormir", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Dormir_Web.m4v", true),
            Palabras("Empezar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Empezar_Web.m4v", true),
            Palabras("Ensenar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Ensenar_Web.m4v", true),
            Palabras("Entender", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Entender_Web.m4v", true),
            Palabras("Escribir", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Escribir_Web.m4v", true),
            Palabras("Esperar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Esperar_Web.m4v", true),
            Palabras("Estudiar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Estudiar_Web.m4v", true),
            Palabras("Explicar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Explicar_Web.m4v", true),
            Palabras("Hablar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Hablar_Web.m4v", true),
            Palabras("Hacer", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Hacer_Web.m4v", true),
            Palabras("Jugar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Jugar_Web.m4v", true),
            Palabras("Limpiar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Limpiar_Web.m4v", true),
            Palabras("Necesitar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Necesitar_Web.m4v", true),
            Palabras("Olvidar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Olvidar_Web.m4v", true),
            Palabras("Pagar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Pagar_Web.m4v", true),
            Palabras("Pensar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Pensar_Web.m4v", true),
            Palabras("Perder", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Perder_Web.m4v", true),
            Palabras("Platicar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Platicar_Web.m4v", true),
            Palabras("Poder", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Poder_Web.m4v", true),
            Palabras("Preguntar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Preguntar_Web.m4v", true),
            Palabras("Sentar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Sentar_Web.m4v", true),
            Palabras("Terminar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Terminar_Web.m4v", true),
            Palabras("Trabajar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Trabajar_Web.m4v", true),
            Palabras("Vender", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Vender_Web.m4v", true),
            Palabras("Ver", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Ver_Web.m4v", true),
            Palabras("Vivir", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosComunes_Web/Vivir_Web.m4v", true),
        )
    ),
    Categorias("Verbos Narrativos","https://cdn-icons-png.flaticon.com/512/3240/3240886.png",
        mutableListOf(
            Palabras("Conocer", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Conocer_Web.m4v", true),
            Palabras("Entender", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Entender_Web.m4v", true),
            Palabras("Gustar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Gustar_Web.m4v", true),
            Palabras("Haber", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Haber_Web.m4v", true),
            Palabras("Noconocer", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Noconocer_Web.m4v", true),
            Palabras("Noentender", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Noentender_Web.m4v", true),
            Palabras("Nogustar", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Nogustar_Web.m4v", true),
            Palabras("Nohaber", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Nohaber_Web.m4v", true),
            Palabras("Nopoder", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Nopoder_Web.m4v", true),
            Palabras("Noquerer", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Noquerer_Web.m4v", true),
            Palabras("Nosaber", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Nosaber_Web.m4v", true),
            Palabras("Noservir", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Noservir_Web.m4v", true),
            Palabras("Poder", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Poder_Web.m4v", true),
            Palabras("Querer", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Querer_Web.m4v", true),
            Palabras("Saber", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Saber_Web.m4v", true),
            Palabras("Servir", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_VerbosNarrativos_Web/Servir_Web.m4v", true),
        )
    ),
    Categorias("Verduras","https://cdn-icons-png.flaticon.com/512/1147/1147832.png",
        mutableListOf(
            Palabras("Aguacate", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Aguacate_Web.m4v", true),
            Palabras("Ajo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Ajo_Web.m4v", true),
            Palabras("Betabel", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Betabel_Web.m4v", true),
            Palabras("Calabacita", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Calabacita_Web.m4v", true),
            Palabras("Calabaza", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Calabaza_Web.m4v", true),
            Palabras("Camote", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Camote_Web.m4v", true),
            Palabras("Cebolla", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Cebolla_Web.m4v", true),
            Palabras("Chicharo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Chicharo_Web.m4v", true),
            Palabras("Chile", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Chile_Web.m4v", true),
            Palabras("Elote", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Elote_Web.m4v", true),
            Palabras("Frijol", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Frijol_Web.m4v", true),
            Palabras("Hongo", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Hongo_Web.m4v", true),
            Palabras("Jitomate", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Jitomate_Web.m4v", true),
            Palabras("Lechuga", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Lechuga_Web.m4v", true),
            Palabras("Nopal", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Nopal_Web.m4v", true),
            Palabras("Papa", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Papa_Web.m4v", true),
            Palabras("Pepino", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Pepino_Web.m4v", true),
            Palabras("Zanahoria", "https://storage.googleapis.com/jd-lsm-u/Videos/LSM_Verduras_Web/Zanahoria_Web.m4v", true)
        )
    )
)

